import type {Metadata} from 'next';
import { Inter } from 'next/font/google'; // Changed font for better minimalist look
import './globals.css';
import { Toaster } from '@/components/ui/toaster'; // Import Toaster

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: '食刻', // Updated app title
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.variable} font-sans antialiased flex flex-col min-h-full`}
      >
        <main className="flex-grow flex flex-col">{children}</main>
        <Toaster /> {/* Add Toaster for notifications */}
      </body>
    </html>
  );
}
